# Generated by Django 4.0.4 on 2022-05-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NiftyFifty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_name', models.CharField(max_length=30)),
                ('index_value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('percent_change', models.FloatField()),
            ],
        ),
    ]
